### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Capt-Zeanie** [realiti4/pip-upgrade#1]
Here is the end of the log when running pip-upgrade on a Raspberry Pi 4.

  Downloading https://files.pythonhosted.org/packages/af/cc/5064a3c25721cd863e6982b87f10fdd91d8bcc62b6f7f36f5231f20d6376/python-augeas-1.1.0.tar.gz (93kB)
    100% |████████████████████████████████| 102kB 2.5MB/s 
    Complete output from command python setup.py egg_info:
      Failed building wheel for cffi
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp9975e_k7', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q8pq7f8r/python-augeas/setup.py", line 43, in <module>
        test_suite="test.test_augeas",
      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 160, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 155, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/dist.py", line 698, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 783, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp9975e_k7', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-q8pq7f8r/python-augeas/
pi@server:~ $

**Comment by realiti4** [comment]
Hi, could you please upgrade to v0.3.7 or newer and try `pip-upgrade` in your console while virtualenv is active? I've redone everything, and it should be more reliable now.

**Comment by realiti4** [comment]
I'm closing this since the tool has changed completely, and this error shouldn't be an issue right now hopefully. Thank you for opening an issue and pointing this out. Please reopen if you are having problems with v0.4.5 or higher.
