### ISSUE TITLE
Typing Extensions Issue

### ISSUE THREAD

**Issue by TabulateJarl8** [realiti4/pip-upgrade#14]
Hi, I figured that I'd let you know that there seems to be an issue with upgrading the `typing_extensions` package that is resolved via manual upgrade
```py
Checking outdated packages...
Traceback (most recent call last):
  File "/home/tabulate/.local/lib/python3.9/site-packages/pip_upgrade/dependencies_base.py", line 36, in get_dependencies
    pkg_store = self.dict[pkg_name]
KeyError: 'typing_extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tabulate/.local/bin/pip-upgrade", line 8, in <module>
    sys.exit(main())
  File "/home/tabulate/.local/lib/python3.9/site-packages/pip_upgrade/main.py", line 70, in main
    pip_upgrade.get_dependencies()
  File "/home/tabulate/.local/lib/python3.9/site-packages/pip_upgrade/dependencies_base.py", line 41, in get_dependencies
    raise e
  File "/home/tabulate/.local/lib/python3.9/site-packages/pip_upgrade/dependencies_base.py", line 39, in get_dependencies
    pkg_store = self.dict[pkg_name.lower()]
KeyError: 'typing_extensions'
```

**Comment by realiti4** [comment]
Hi, this should be fixed with v0.6.2. I updated as soon as I realized, but since `typing_extensions` is in the `outdated` packages list, it crashes pip-upgrade for everyone and new update prompt can't be seen unfortunately. Hopefully it fixed the issue. 

Can you please try the latest version, thanks.
